Fix sshd handlers for Debian 12.
geerlingguy/ansible-role-security pull request #135
Opened 2024-09-26 16:06 UTC by klemens-st

Debian 12, Ubuntu 22 and above need to re-run systemd generators to pull the updated sshd port config.

Just changing sshd_config has no effect, sshd still listens on default port 22.

In this PR I add an additional handler for Debian that simply runs `systemctl daemon-reload`. This forces systemd to rerun its generators.

https://discourse.ubuntu.com/t/sshd-now-uses-socket-based-activation-ubuntu-22-10-and-later/30189/14

2024-10-26 11:24 UTC, YogSottot commented
Is there a reason to use the command module rather than systemd?

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html#examples

```
- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd_service:
    daemon_reload: true
```

2025-02-18 16:05 UTC, geerlingguy requested changes

2025-02-18 16:05 UTC, geerlingguy commented on handlers/main.yml
> +  ansible.builtin.command: systemctl daemon-reload
Also please name the handler "reload systemd"

2025-02-18 16:05 UTC, geerlingguy commented on vars/RedHat.yml
> +security_sshd_handlers: restart ssh
Do you know if it's not also required on RedHat? It seems like it would be safe to default to it for both Linux flavors.

2025-03-03 14:23 UTC, klemens-st commented on vars/RedHat.yml
> +security_sshd_handlers: restart ssh
It's not required on RedHat, there's no mention of it in the available docs. It doesn't seem they're planning to go that way - I tested Fedora 41 and was able to change the port without reloading systemd.

But sure, it's sefe to default to it for both, I'll remove the additional variable.

2025-03-03 15:54 UTC, merged